accounts:
  - name: user1
    coins: ["1000tpp", "100000000stake"]
  - name: user2
    coins: ["5000tpp"]
  - name: user3
    coins: ["500tpp"]
  - name: user4
    coins: ["500tpp"]
  - name: faucet
    coins: ["100000000tpp"]

validator:
  name: user1
  staked: "100000000stake"
