accounts:
  - name: user1
    coins: ["10000tpp", "1000000stake"]
  - name: user2
    coins: ["50000tpp"]
  - name: user3
    coins: ["5000tpp"]
  - name: user4
    coins: ["5000tpp"]
  - name: faucet
    coins: ["100000000tpp"]

validator:
  name: user1
  staked: "100000000stake"
