accounts:
  - name: user1
    coins: ["1000tpp", "1000000stake"]
  - name: user2
    coins: ["500tpp"]
  - name: ModuleName
    coins: ["500tpp"]
  - name: faucet
    coins: ["100000000tpp"]
  - name: tpp
    coins: ["100tpp"]
validator:
  name: user1
  staked: "1000000stake"
