accounts:
  - name: user1
    coins: ["200000000utrst"]
  - name: user2
    coins: ["500000utrst"]
  - name: user3
    coins: ["50000utrst"]
  - name: user4
    coins: ["50000utrst"]
  - name: faucet
    coins: ["1000000000utrst"]
    mnemonic: "yellow reveal rubber dumb picture cargo valid cover define inner demand solve panel behave analyst build edit stereo hope initial feed rare bleak army"

validator:
  name: user1
  staked: "100000000utrst"

genesis:
  chain_id: "trst_chain_1"
    app_state: 
      staking: 
        params: 
          bond_denom: "utrst"

client:
  vuex:
    path: "js"