version: '3'

services:
  bootstrap:
    image: trstlabs/trustless-hub-sw-dev-custom-bootstrap:latest
    container_name: bootstrap
    volumes:
#      - /tmp/trstcli:/root/.trstcli
      - /tmp/trstd-bootstrap:/root/.trstd
      - /tmp/sgx_secrets:/opt/trustlesshub/.sgx_secrets
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657
      - 1317
      - 1337
    ports:
      - 26657:26657
      - 26656:26656
      - 1317:1317
      - 1337:1337

#  node:
#    image: trstlabs/trustless-hub-sw-dev-custom-node:latest
#    container_name: node
#    depends_on:
#      - bootstrap
#    volumes:
#      - /tmp/trstd-bootstrap:/tmp/.trstd
##      - /tmp/trstdbootstrap:/tmp/.trstd
#      - /tmp/trstd-node:/root/.trstd
#      - /tmp/trstcli:/root/.trstcli
##      - /tmp/sgx_secrets:/root/.sgx_secrets
#    stdin_open: true
#    tty: true
#    environment:
#      - http_proxy
#      - https_proxy
#    ports:
#      - 26657:26657
