[package]
name = "trustless-cosmwasm-std"
version = "0.10.0"
authors = ["TRST Labs <info@trstlabs.xyz>"]
edition = "2018"
description = "Standard library for Wasm based smart contracts on Cosmos blockchains"
repository = "https://github.com/trstlabs/trst/tree/master/cosmwasm/packages/std"
license = "Apache-2.0"
readme = "README.md"

[badges]
#circle-ci = { repository = "CosmWasm/cosmwasm", branch = "master" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["staking", "stargate"]

[features]
default = ["staking", "stargate"]
# iterator allows us to iterate over all DB items in a given range
# optional as some merkle stores (like tries) don't support this
# given Ethereum 1.0, 2.0, Substrate, and other major projects use Tries
# we keep this optional, to allow possible future integration (or different Cosmos Backends)
iterator = []
# staking exposes bindings to a required staking moudle in the runtime, via new
# CosmosMsg types, and new QueryRequest types. This should only be enabled on contracts
# that require these types, so other contracts can be used on systems with eg. PoA consensus
staking = []
# backtraces provides much better context at runtime errors (in non-wasm code)
# at the cost of a bit of code size and performance.
# This feature requires Rust nightly because it depends on the unstable backtrace feature.
backtraces = []
# stargate enables stargate-dependent messages and queries, like raw protobuf messages
# as well as ibc-related functionality
stargate = []
# Debug prints enable printing log messages to the logging system of the enclave
# from inside your contract. This will only work in enclaves compiled in SW mode
# and loading the contract for execution will fail if this is used a HW mode
# enclave. This is done in order to provent leaking secrets in production.
debug-print = []

[dependencies]
base64 = "0.13.0"
serde-json-wasm = { version = "0.3.1" }
schemars = "0.8.1"
cosmwasm-derive = { path = "../derive", version = "1.0.0" }
uint = "=0.9.1"
serde = { version = "1.0.117", default-features = false, features = [
    "derive",
    "alloc"
] }
thiserror = "1.0"
snafu = { version = "0.6.6" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosmwasm-crypto = { path = "../crypto", version = "1.0.0" }

[dev-dependencies]
cosmwasm-schema = { path = "../schema" }
# The chrono dependency is only used in an example, which Rust compiles for us. If this causes trouble, remove it.
chrono = "0.4"
hex = "0.4"
hex-literal = "0.3.1"