[global]
# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'info'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'intento-test-1'
rpc_addr = 'http://into1:26657'
grpc_addr = 'http://into1:9090'
event_source = { mode = 'push', url = 'ws://into1:26657/websocket', batch_delay = '500ms' }
# websocket_addr = 'ws://into1:26657/websocket'
rpc_timeout = '30s'
account_prefix = 'into'
key_name = 'rly1'
store_prefix = 'ibc'
gas_price = { price = 0.02, denom = 'uinto' }
gas_multiplier = 1.5
#clock_drift = '30s'
max_block_time = '30s'
# trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[[chains]]
id = 'GAIA'
rpc_addr = 'http://gaia1:26657'
grpc_addr = 'http://gaia1:9090'
event_source = { mode = 'push', url = 'ws://gaia1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'rly2'
store_prefix = 'ibc'
gas_price = { price = 0.02, denom = 'uatom' }
default_gas = 100000
max_gas = 5000000
gas_multiplier = 1.7
#clock_drift = '10s'
max_block_time = '30s'
#trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[[chains]]
id = 'OSMO'
rpc_addr = 'http://osmo1:26657'
grpc_addr = 'http://osmo1:9090'
event_source = { mode = 'push', url = 'ws://osmo1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '30s'
account_prefix = 'osmo'
key_name = 'rly4'
store_prefix = 'ibc'
gas_price = { price = 0.02, denom = 'uosmo' }
default_gas = 100000
max_gas = 5000000
gas_multiplier = 1.7
#clock_drift = '30s'
max_block_time = '30s'
#trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

# [[chains]]
# id = 'osmo-test-5'
# rpc_addr = 'http://142.93.175.50:26657' #'https://rpc.osmotest5.osmosis.zone:443' #
# grpc_addr = 'http://142.93.175.50:9090' #'https://grpc.osmotest5.osmosis.zone:443'#'#
# #event_source = { mode = 'push', url = 'ws://rpc.osmotest5.osmosis.zone:443/websocket', batch_delay = '500ms' }
# event_source = { mode = 'push', url = 'ws://142.93.175.50/websocket', batch_delay = '500ms' }
# rpc_timeout = '60s'
# account_prefix = 'osmo'
# key_name = 'rly4'
# store_prefix = 'ibc'
# default_gas = 100000
# max_gas = 3000000
# gas_price = { price = 0.03, denom = 'uosmo' }
# gas_multiplier = 1.3
# max_msg_num = 30
# max_tx_size = 2097152
# clock_drift = '20s'
# max_block_time = '30s'
# trusting_period = '431000s'
# trust_threshold = { numerator = '1', denominator = '3' }
# address_type = { derivation = 'cosmos' }